export const events = [
    {
        slug: "react-conf-2024",
        image: "/images/event1.png",
        title: "React Conf 2024",
        location: "San Francisco, CA",
        date: "2024-03-15",
        time: "9:00 AM - 6:00 PM",
    },
    {
        slug: "nextjs-summit",
        image: "/images/event2.png",
        title: "Next.js Summit",
        location: "Austin, TX",
        date: "2024-04-22",
        time: "10:00 AM - 5:00 PM",
    },
    {
        slug: "javascript-world",
        image: "/images/event3.png",
        title: "JavaScript World Conference",
        location: "New York, NY",
        date: "2024-05-08",
        time: "8:30 AM - 7:00 PM",
    },
    {
        slug: "ai-hackathon-2024",
        image: "/images/event4.png",
        title: "AI Innovation Hackathon",
        location: "Seattle, WA",
        date: "2024-06-14 to 2024-06-16",
        time: "48 Hours",
    },
    {
        slug: "web3-developer-meetup",
        image: "/images/event5.png",
        title: "Web3 Developer Meetup",
        location: "Miami, FL",
        date: "2024-07-20",
        time: "6:00 PM - 9:00 PM",
    },
    {
        slug: "fullstack-conference",
        image: "/images/event6.png",
        title: "Full Stack Conference",
        location: "Denver, CO",
        date: "2024-08-12",
        time: "9:00 AM - 6:00 PM",
    },
    {
        slug: "devops-unleashed",
        image: "/images/event1.png",
        title: "DevOps Unleashed",
        location: "Chicago, IL",
        date: "2024-09-05",
        time: "8:00 AM - 5:30 PM",
    },
    {
        slug: "mobile-dev-summit",
        image: "/images/event2.png",
        title: "Mobile Development Summit",
        location: "Los Angeles, CA",
        date: "2024-10-18",
        time: "9:30 AM - 6:00 PM",
    },
    {
        slug: "cybersecurity-conference",
        image: "/images/event3.png",
        title: "Cybersecurity Conference",
        location: "Boston, MA",
        date: "2024-11-02",
        time: "8:00 AM - 7:00 PM",
    },
    {
        slug: "data-science-hackathon",
        image: "/images/event4.png",
        title: "Data Science Hackathon",
        location: "San Diego, CA",
        date: "2024-12-07 to 2024-12-09",
        time: "72 Hours",
    },
    {
        slug: "cloud-native-meetup",
        image: "/images/event5.png",
        title: "Cloud Native Meetup",
        location: "Portland, OR",
        date: "2025-01-15",
        time: "6:30 PM - 9:00 PM",
    },
    {
        slug: "frontend-masters",
        image: "/images/event6.png",
        title: "Frontend Masters Conference",
        location: "Nashville, TN",
        date: "2025-02-28",
        time: "9:00 AM - 5:00 PM",
    },
];
